[package]
name = "adkfjakdjk"
version = "0.2.0"
edition = "2021"
authors = ["Sadık Kuzu <sadikkuzu@hotmail.com>"]
license = "MIT"
description = "A tool to greet adkfjakdjk"
readme = "README.md"
keywords = ["cli", "random", "demo"]
categories = ["command-line-utilities"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.0", features = ["derive"] }
