name: Publish to crates.io

on:
    workflow_dispatch:
    release:
      types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Rust
      uses: actions-rs/toolchain@master
      with:
        toolchain: stable
        override: true

    - name: Publish to crates.io
      run: |
        cargo login ${{ secrets.CRATES_IO_TOKEN }}
        cargo publish
      env:
        CARGO_NET_GIT_FETCH_WITH_CLI: true
      # Ensure the secret is available as an environment variable
